// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxHfk7TuPo9irDPQ8JLOHbK6zbCbWLKKE',
    appId: '1:451669329476:web:1a95aed31dbf07ce975e11',
    messagingSenderId: '451669329476',
    projectId: 'testchatbotalimipfa',
    authDomain: 'testchatbotalimipfa.firebaseapp.com',
    storageBucket: 'testchatbotalimipfa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfOwt9YWlwUeuKtu53nAmsbgkRAmLjnbk',
    appId: '1:451669329476:android:ccc17c6b86cbe27c975e11',
    messagingSenderId: '451669329476',
    projectId: 'testchatbotalimipfa',
    storageBucket: 'testchatbotalimipfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1XanZAtSbYxPuwO5aTxRPbclHbAp9Oi8',
    appId: '1:451669329476:ios:3c209be2f6c2f1e6975e11',
    messagingSenderId: '451669329476',
    projectId: 'testchatbotalimipfa',
    storageBucket: 'testchatbotalimipfa.appspot.com',
    iosBundleId: 'com.example.wellbeingGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1XanZAtSbYxPuwO5aTxRPbclHbAp9Oi8',
    appId: '1:451669329476:ios:3c209be2f6c2f1e6975e11',
    messagingSenderId: '451669329476',
    projectId: 'testchatbotalimipfa',
    storageBucket: 'testchatbotalimipfa.appspot.com',
    iosBundleId: 'com.example.wellbeingGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxHfk7TuPo9irDPQ8JLOHbK6zbCbWLKKE',
    appId: '1:451669329476:web:bc51144721a1a748975e11',
    messagingSenderId: '451669329476',
    projectId: 'testchatbotalimipfa',
    authDomain: 'testchatbotalimipfa.firebaseapp.com',
    storageBucket: 'testchatbotalimipfa.appspot.com',
  );

}